package io.gutapk.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

// A language appears in the list only once its table is complete, so the
// user never picks a language and reads English. Adding one is an entry
// here plus a table below, nothing else. rtl flips the whole layout.
enum class Lang(val code: String, val native: String, val english: String, val rtl: Boolean) {
    EN("en", "English", "English", false),
    FR("fr", "Français", "French", false),
}

fun langOf(code: String?): Lang? = Lang.entries.firstOrNull { it.code == code }

fun detectLang(): Lang {
    val env = System.getenv("LC_ALL") ?: System.getenv("LC_MESSAGES") ?: System.getenv("LANG") ?: "en"
    return langOf(env.substringBefore('_').substringBefore('.')) ?: Lang.EN
}

val LocalLang = staticCompositionLocalOf { Lang.EN }

@Composable
fun t(key: String, vararg args: Any): String {
    val raw = Strings.get(LocalLang.current, key)
    return if (args.isEmpty()) raw else raw.format(*args)
}

// Stays in English whatever the language. A licence notice travels with the
// program and must stay readable by whoever receives it.
const val LICENCE_TEXT = """GutapK, Copyright (C) 1448 Hijri, the GutapK authors.

This program comes with ABSOLUTELY NO WARRANTY.
It is free software, and you are welcome to redistribute it under the
terms of the GNU General Public License, version 3 or any later version.

The packages this tool opens, edits or clones stay under their own
licences, held by their authors."""

object Strings {
    fun get(lang: Lang, key: String): String = tables[lang]?.get(key) ?: en[key] ?: key

    val en: Map<String, String> = mapOf(
        "continue" to "Continue",
        "back" to "Back",
        "close" to "Close",
        "browse" to "Browse",
        "choose_apk" to "Choose an APK or a split set",
        "accept" to "Understood, continue",
        "decline" to "Decline and quit",
        "step_legal" to "Legal",
        "step_root" to "Folder",

        "lang_title" to "Language",

        "lic_title" to "Licence",

        "legal_title" to "Licensing and trademarks",
        "legal_body" to """GutapK modifies apps written by other people. Their authors keep their rights, and their licence travels with every copy.

Using and modifying an app on your own device is your business. Obligations begin when you GIVE the modified APK to someone else.

Free software licences allow modification, under conditions. Apache-2.0: keep the LICENSE and NOTICE files, and state that you changed the code. GPL-3.0: the same, plus you must offer the recipient the complete source of YOUR modified version, under the GPL, with no added restriction.

Proprietary apps: their terms usually forbid modifying or redistributing them. Keep what you change for yourself, and read the terms before you share anything.

Names, logos and icons are often trademarks. Do not present a modified app as the original or as an official one. This is why GutapK lets you rename an app and change its icon.

A modified APK is signed with your own key. It is not built, reviewed or endorsed by the original authors, and it comes with no warranty.

This is a plain-language summary, not legal advice.""",
        "legal_accepted" to "Accepted, revision %s",

        "root_title" to "Where should GutapK keep everything?",
        "root_body" to "This folder holds the downloaded tools, the work folders, the logs and every opened package. GutapK writes nowhere else, except its settings.",
        "root_field" to "Folder",
        "root_bad_absolute" to "Give a full path, starting with / or ~.",
        "root_bad_forbidden" to "The system empties temporary and cache folders. Choose a folder that lasts.",
        "root_bad_write" to "This folder cannot be created or written to.",
        "root_next_launch" to "Applies at the next launch. What is already under the old folder stays there.",

        "home_source" to "Start",
        "src_apk" to "Edit an APK",
        "src_apk_d" to "Pick an APK or a split set, or drop it on this window",
        "src_device" to "ADB device",
        "src_device_d" to "Debloat, pull and install apps on a phone connected over ADB",
        "drop_here" to "Drop to open",
        "drop_not_apk" to "GutapK opens .apk files and split sets (.apks, .xapk, .apkm).",
        "not_yet" to "Not yet",
        "available" to "Available",
        "footer" to "GutapK %s. Free software under the GNU GPL 3.0 or later, with absolutely no warranty.",

        "settings" to "Settings",
        "set_general" to "General",
        "set_language" to "Language",
        "set_theme" to "Theme",
        "set_accent" to "Colour",
        "accent_system" to "Default, GNOME sets no accent colour",
        "accent_system_named" to "Same as GNOME, %s",
        "accent_blue" to "Blue",
        "accent_teal" to "Teal",
        "accent_green" to "Green",
        "accent_yellow" to "Yellow",
        "accent_orange" to "Orange",
        "accent_red" to "Red",
        "accent_pink" to "Pink",
        "accent_purple" to "Purple",
        "accent_slate" to "Slate",
        "theme_system" to "Same as the system",
        "theme_system_light" to "Same as the system, light detected",
        "theme_system_dark" to "Same as the system, dark detected",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "set_storage" to "Storage",
        "set_root" to "Root folder",
        "set_legal" to "Legal",
        "set_licence_d" to "GNU GPL 3.0 or later",
        "set_about" to "About",
        "about_version" to "Version",
        "about_config" to "Settings folder",
        "set_tools" to "Tools",
        "tool_missing" to "Not installed. Click to look up the latest version.",
        "tool_ok" to "Version %s, verified, sha256 %s",
        "tool_checking" to "Installed, being checked",
        "tool_modified" to "Changed since install. It will not run until checked again.",
        "tool_failed" to "Failed: %s",
        "tool_state_missing" to "Not installed",
        "tool_state_ok" to "Verified",
        "tool_state_bad" to "Changed",
        "tool_location" to "Location",
        "tool_archive" to "Archive sha256",
        "tool_entry" to "Program sha256",
        "job_download" to "Downloading",
        "job_check" to "Checking",
        "job_extract" to "Extracting",
        "cancel" to "Cancel",
        "dl_title" to "%s",
        "dl_what" to "What",
        "dl_from" to "From",
        "dl_size" to "Size",
        "dl_where" to "Lands in",
        "dl_licence" to "Licence",
        "dl_checks" to "Checks",
        "dl_checks_v" to "Size and checksum as published by the source. The sha256 of each version is recorded on first download and checked before every use.",
        "dl_go" to "Download",
        "home_recent" to "Recent",
        "imp_failed" to "This file could not be opened",
        "job_read" to "Reading",
        "job_copy" to "Copying",
        "ov_reading" to "Reading the package",
        "ov_error" to "Unreadable",
        "ov_identity" to "Identity",
        "ov_package" to "Package",
        "ov_version" to "Version",
        "ov_min_sdk" to "Minimum SDK",
        "ov_target_sdk" to "Target SDK",
        "ov_split" to "Split of a bundle",
        "ov_signature" to "Signature",
        "ov_sig_state" to "State",
        "ov_sig_ok" to "Valid, schemes %s",
        "ov_sig_bad" to "Not verified. Unsigned, or changed after signing.",
        "ov_sig_badge_ok" to "Valid",
        "ov_sig_badge_bad" to "Invalid",
        "ov_content" to "Content",
        "ov_dex" to "Dex files",
        "ov_abis" to "ABIs",
        "ov_libs" to "Native libraries",
        "ov_engines" to "Engines",
        "ov_trackers" to "Trackers",
        "ov_trk_look" to "Look for trackers",
        "ov_trk_look_d" to "Compares the app's code with the tracker list of Exodus Privacy. The list is downloaded once, its facts shown first.",
        "ov_trk_none" to "No known tracker",
        "ov_trk_none_d" to "None of the %s trackers in the list matched. A library whose names were shrunk away is not seen.",
        "ov_trk_uncat" to "Not categorised",
        "ov_trk_credit" to "Tracker list by Exodus Privacy, downloaded %s, Open Database License.",
        "trk_title" to "Exodus Privacy tracker list",
        "trk_what" to "The code signatures of about 400 trackers, the list Exodus Privacy maintains.",
        "ov_code" to "Code",
        "ov_code_detail" to "%s dex files, %s native libraries",
        "ov_signer" to "Signer",
        "ov_algorithm" to "Algorithm",
        "ov_permissions_all" to "See all permissions",
        "ov_permissions_more" to "%s and %s more",
        "ov_permissions_none" to "No permission",
        "ov_permissions_none_detail" to "The app asks for nothing.",
        "ov_entries" to "Files in the archive",
        "ov_none" to "None",
        "ov_file" to "File",
        "ov_location" to "Copy under the root",
        "ov_licence_note" to "The licence of this package is not known to GutapK. Check it before sharing anything built from it.",
        "ov_permissions" to "Permissions, %s",
        "dl_version" to "Version",
        "dl_looking" to "Looking up the latest version at %s",
        "dl_lookup_failed" to "%s could not be reached: %s",
        "retry" to "Retry",
        "self_title" to "GutapK %s is available",
        "self_replaces" to "Replaces",
        "self_body" to "The new AppImage is downloaded under the root, checked against the sha256 GitHub publishes, then takes the place of this one. The current file is kept beside it with .old added. Restart GutapK to use the new version.",
        "self_done_title" to "GutapK updated",
        "self_done" to "%s is the new version. Restart GutapK to use it. The previous one is kept beside it as .old.",
        "self_failed_title" to "Update failed",
        "self_failed" to "%s. The current AppImage is unchanged.",
        "job_replace" to "Replacing",
        "upd_title" to "Tool update available",
        "upd_go" to "Update",
        "upd_later" to "Later",
        "upd_skip" to "Skip this version",
        "upd_none" to "Up to date. %s is the latest version.",
        "upd_check" to "Check for update",
        "upd_auto" to "Check for updates at launch",
        "upd_auto_d" to "Asks GitHub and the tool publishers for newer versions of GutapK and of the installed tools. Nothing is downloaded without your OK.",
        "disk_title" to "Disk usage",
        "disk_row" to "What GutapK keeps under the root, and its weight",
        "disk_summary" to "Root",
        "disk_scanning" to "Measuring",
        "disk_total" to "%s in total",
        "disk_empty" to "Empty",
        "disk_more" to "and %s older ones, %s",
        "disk_protected" to "Kept, in use or needed to check the tools",
        "disk_deletable" to "Can be deleted",
        "disk_delete_q" to "Delete %s?",
        "disk_delete_body" to "%s will be freed. This cannot be undone.",
        "delete" to "Delete",
        "sec_dependencies" to "Downloaded tools",
        "sec_work" to "Work folders",
        "sec_logs" to "Logs",
        "sec_packages" to "Packages",
        "sec_other" to "Other files under the root",
        "clean_title" to "Free up space",
        "clean_go" to "Free %s",
        "clean_note" to "Logs, packages and the signing key are left alone. Tools are downloaded again when needed, and held to the fingerprints already recorded.",
        "clean_below" to "Cleanup is offered past %s. Below that, the %s of downloads and work folders are a cache worth keeping, not waste.",
        "job_clean" to "Freeing space",
        "sign_action" to "Sign",
        "sign_title" to "Sign this APK",
        "sign_key" to "Key",
        "sign_key_none" to "Not chosen yet",
        "sign_choose" to "Choose a key",
        "sign_change" to "Change",
        "sign_schemes" to "Signature schemes",
        "sign_output" to "Signed file",
        "sign_go" to "Sign",
        "sign_test_warning" to "The Android test key is public. Anyone can sign with it, so an APK signed with it proves nothing about who made it. Use it for testing only.",
        "sign_install_note" to "Android will not install this APK over an app signed with another key. Uninstall that app first, and its data goes with it.",
        "signed_title" to "Signed and verified",
        "signed_file" to "File",
        "signed_signer" to "Certificate SHA-256",
        "signed_schemes" to "Verified schemes",
        "sign_failed" to "Signing failed",
        "show_folder" to "Show in folder",
        "job_sign" to "Signing",
        "job_verify" to "Verifying",
        "key_title" to "Signing key",
        "key_test" to "Android test key",
        "key_test_d" to "Public, for testing only",
        "key_own" to "Your own key",
        "key_own_new" to "Created the first time you choose it. The file stays in the settings folder, its password in the system keyring.",
        "key_own_ready" to "Ready, SHA-256 %s…",
        "create_title" to "Create your signing key",
        "create_what_v" to "An RSA 4096 key and a self-signed certificate named GutapK signing key, valid for 30 years.",
        "create_password" to "Password",
        "create_password_v" to "Random, kept in the system keyring as GutapK signing keystore. The keyring may ask for your login password.",
        "create_backup" to "Back up the key file and keep its keyring entry. Android only updates an app signed with the same key. If either is lost, the app has to be uninstalled, with its data, before a new version installs.",
        "create_go" to "Create",
        "creating" to "Creating your key",
        "creating_note" to "Generating a 4096-bit key takes a few seconds. The keyring may ask for your login password.",
        "create_failed" to "The key could not be created",
        "own_missing" to "Your own key is chosen, but %s is missing. Put the file back, or choose another key.",
        "set_key_file" to "Key file",
        "job_keygen" to "Generating the key",
        "job_keystore" to "Writing the keystore",
        "job_keyring" to "Saving to the keyring",
        "set_signing" to "Signing",
        "set_sign_key" to "Signing key",
        "edit_permissions" to "Permissions",
        "edit_perm_note" to "Switch a permission off to remove it. This can stop a feature working. Adding permissions is not offered, an app cannot be granted more than it was built to ask for.",
        "edit_title" to "Edit this app",
        "edit_min_sdk" to "Min SDK",
        "edit_target_sdk" to "Target SDK",
        "ok" to "OK",
        "edit_changed" to "Changed",
        "edit_nothing_yet" to "Change something to rebuild",
        "edit_needs_key" to "Choose a signing key to rebuild",
        "edit_zone_sdk" to "Android versions",
        "edit_zone_icon" to "Icon",
        "edit_zone_signing" to "Signing",
        "edit_retry" to "Retry with apktool",
        "edit_retry_note" to "APKEditor could not rebuild this app. apktool, the second engine, rebuilds with Google's aapt2 and can succeed where APKEditor fails. It is downloaded and checked first if it is not installed, every step in the job log.",
        "edit_zone_modern" to "Modernise",
        "edit_back" to "Predictive back",
        "edit_back_d" to "Android 14 and later preview the screen you go back to during the gesture. An app that still catches Back the old way may stop closing its own panels with it.",
        "edit_back_done" to "Already on.",
        "edit_locales" to "App languages",
        "edit_locales_d" to "Android 13 and later let you pick this app's language in Settings, among the languages it is translated into.",
        "edit_locales_done" to "Already listed in Settings.",
        "edit_libs" to "Native libraries from the APK",
        "edit_libs_d" to "Libraries stay stored in the APK instead of being copied at install: less storage and a faster install.",
        "edit_libs_done" to "Already read from the APK.",
        "edit_libs_none" to "This app has no native library.",
        "edit_trk_first" to "Look for trackers in the overview first, it downloads Exodus Privacy's list.",
        "edit_trk_none" to "No known tracker in this app.",
        "edit_trk_note" to "A silenced tracker has its components disabled and, for Firebase and Facebook, the opt-out switches its makers document set. Code the app calls itself still runs.",
        "edit_trk_parts" to "%s components disabled",
        "edit_trk_no_parts" to "No component of its own, opt-out settings only",
        "edit_trk_ads" to "An ad library: the app can crash when it tries to show an ad.",
        "edit_adid" to "Advertising ID",
        "edit_adid_d" to "Removes the permission to read the advertising ID. Android 13 and later then give the app only zeros.",
        "edit_zone_size" to "Size",
        "edit_abi" to "Architectures",
        "edit_abi_one" to "Only %s, nothing to remove.",
        "edit_abi_all" to "All kept: %s. Phones today are arm64-v8a.",
        "edit_abi_only" to "%s only",
        "edit_abi_keep_all" to "Keep all",
        "edit_langs" to "Languages",
        "edit_langs_one" to "One language only, nothing to remove.",
        "edit_langs_all" to "All %s kept.",
        "edit_langs_some" to "%s of %s kept. The others fall back to the app's default language.",
        "edit_debuginfo" to "Debug information",
        "edit_debuginfo_d" to "Drops line numbers and variable names from the code. A crash report then shows no line. Small on apps already shrunk by their maker.",
        "edit_zone_security" to "Security",
        "edit_nobackup" to "No backup",
        "edit_nobackup_d" to "The app's data stays out of Google's cloud backup and of adb backup. On Android 12 and later, a transfer to a new phone follows the app's own rules.",
        "edit_nobackup_done" to "Backup already off.",
        "edit_net" to "Strict network",
        "edit_net_d" to "Refuses plain http and certificates added by the user, the ones used to watch traffic. An app that talks to a device on your network over plain http, a camera or a printer, can lose that.",
        "edit_fragile" to "Ask before deleting data",
        "edit_fragile_d" to "Uninstalling asks whether to keep the app's data, so a reinstall finds it again.",
        "edit_fragile_done" to "Already asks.",
        "edit_memtag" to "Memory tagging",
        "edit_memtag_d" to "On phones with memory tagging, Pixel 8 and later, memory errors are caught instead of exploited. A faulty app can then stop where it used to carry on.",
        "edit_memtag_done" to "Already on.",
        "edit_debug" to "Not debuggable",
        "edit_debug_d" to "This app is debuggable: any computer it is plugged into can read its data. Switch it off for everyday use.",
        "edit_debug_done" to "Not debuggable, as it should be.",
        "edit_package" to "Package id",
        "edit_package_note" to "A new id makes a clone that installs beside the original. The id, its providers and its own permissions also change where the code and resources write them whole. Google services tied to the original id, sign-in or maps for instance, stop working in the clone.",
        "edit_package_format" to "Lowercase words joined by dots, each starting with a letter, like com.example.app.",
        "edit_package_reserved" to "Reserved for Android, Google or a system: android, com.android, com.google, org.lineageos, org.grapheneos.",
        "edit_icon_image" to "Replace with an image",
        "edit_icon_image_d" to "A square PNG, at least %s px. Placed in the icon's safe zone, over the app's own background.",
        "edit_icon_image_ok" to "%s, %s px",
        "edit_icon_clear" to "Remove",
        "edit_icon_not_png" to "%s is not a PNG file.",
        "edit_icon_not_square" to "%s is not square.",
        "edit_icon_too_small" to "%s is %s px, at least %s px is needed.",
        "edit_icon_unreadable" to "%s cannot be read as an image.",
        "edit_themed_icon" to "Themed icon",
        "edit_themed_note" to "Lets Android 13 and later tint the icon with your wallpaper colours. Built from the icon's foreground, best with a logo on a transparent background.",
        "edit_themed_done" to "Already themed, nothing to add.",
        "edit_themed_legacy" to "Not available: the icon is a plain image, not an adaptive icon.",
        "edit_themed_none" to "Not available: the app declares no icon.",
        "rename_action" to "Edit",
        "rename_title" to "Rename this app",
        "rename_field" to "Display name",
        "rename_go" to "Rebuild and sign",
        "rename_needs_tool" to "APKEditor is needed to rebuild the APK. It will be downloaded and checked the first time, with the facts shown before anything is fetched.",
        "job_decode" to "Decoding",
        "job_edit" to "Editing",
        "job_build" to "Rebuilding",
        "apk_filter" to "APK and split sets",
        "job_merge" to "Merging the split set",
        "set_incomplete" to "This split set is incomplete",
        "set_found" to "Found: %s",
        "set_add" to "Add files",
        "set_no_apk" to "No APK was found in these files.",
        "set_no_base" to "The base APK is missing. It is usually named base.apk, or after the app.",
        "set_several_bases" to "Several base APKs were given. Keep the files of one app and one version.",
        "set_mixed_packages" to "These files belong to different apps: %s.",
        "set_mixed_versions" to "These files come from different versions of the app.",
        "set_duplicate" to "The part %s was given twice, in two different versions.",
        "set_missing_types" to "Parts are missing: %s.",
        "set_missing_unknown" to "The base APK needs its split parts, and none were given.",
        "set_unity_lib" to "This is a Unity game and its engine library is missing. Add the part named after the processor, for example split_config.arm64_v8a.apk.",
        "set_type_abi" to "processor (ABI)",
        "set_type_density" to "screen density",
        "set_type_language" to "language",
        "set_merge_needs" to "APKEditor merges the parts into one APK that GutapK can read and edit.",
        "ov_set" to "Split set",
        "ov_set_d" to "%s parts merged: %s",
        "ov_obb" to "Expansion files (OBB)",
        "ov_obb_note" to "Expansion files are not part of the APK and were not merged. They go to the device on their own.",
        "un_title" to "Unity",
        "un_version" to "Unity version",
        "un_unknown" to "Not found",
        "un_backend" to "Scripting backend",
        "un_il2cpp" to "IL2CPP, C# compiled to native code",
        "un_mono" to "Mono, C# kept as .NET assemblies",
        "un_engine_abis" to "Engine built for",
        "un_missing" to "Missing",
        "un_metadata" to "Metadata",
        "un_metadata_version" to "version %s",
        "un_metadata_unreadable" to "header not recognised",
        "un_assemblies" to "Assemblies",
        "un_assemblies_d" to "%s .dll files in assets/bin/Data/Managed",
        "un_no_metadata" to "No global-metadata.dat was found. The game may rename it or embed it in the library, which a dump cannot read as it is.",
        "un_protected" to "The metadata does not start with IL2CPP's signature. It is most likely encrypted or obfuscated, and a dump will fail on it as it is.",
        "un_no_lib" to "libil2cpp.so is missing. If this APK was part of a split set, open the whole set.",
        "job_dump" to "Dumping the IL2CPP code",
        "un_methods" to "Methods",
        "un_methods_d" to "%s methods with their offsets, for %s",
        "un_methods_none" to "Not dumped yet. Cpp2IL reads the game and lists every method with its offset in libil2cpp.so.",
        "un_dump_needs" to "Cpp2IL lists every method of the game with its offset in libil2cpp.so. It publishes pre-releases only.",
        "un_dump_failed" to "The dump failed",
        "me_title" to "Methods",
        "me_source" to "%s methods, %s, Unity %s",
        "me_search" to "Search a namespace, type or method",
        "me_hint" to "Type part of a name. Several words narrow the search, in any order.",
        "me_none" to "No method matches.",
        "me_count" to "%s matches",
        "me_length" to "%s bytes",
        "me_more" to "Only the first %s are shown. Add a word to narrow the search.",
        "un_patches" to "Byte patches",
        "un_patches_d" to "%s saved, applied when rebuilding",
        "hex_edit" to "Change bytes",
        "hex_zone" to "Bytes in libil2cpp.so, %s",
        "hex_where" to "Offset in the file",
        "hex_truncated" to "Only the first %s bytes of this method are shown and can be changed.",
        "hex_patches" to "Patches in this method, %s",
        "hex_patches_none" to "None yet.",
        "hex_not_applied" to "Patches are saved with this package and applied by Rebuild and sign, on the Edit screen.",
        "hex_remove_title" to "Remove this patch?",
        "hex_remove" to "Remove",
        "hex_offset" to "Offset, hex",
        "hex_bytes" to "New bytes, hex",
        "hex_bytes_help" to "Pairs of hex digits, spaces allowed, for example 20 00 80 52",
        "hex_bad" to "Pairs of hex digits only, 0 to 9 and A to F.",
        "hex_range" to "Stay between %s and %s, inside this method.",
        "hex_same" to "These are the bytes already there.",
        "hex_overlap" to "This overlaps the patch at %s. Remove it first.",
        "hex_replaces" to "Replaces %s",
        "hex_save" to "Save",
        "edit_patches" to "Apply %d byte patches",
        "edit_patches_d" to "Each patch checks the bytes it replaces first. If one does not match, nothing is written and the rebuild stops.",
        "edit_patches_abi" to "Patches are made for %s, which the processor setting above removes. Keep that processor or switch the patches off.",
        "edit_patches_blocked" to "Patches need a removed processor",
        "edit_sdk_range" to "Between %d and %d.",
        "edit_sdk_min_above" to "The minimum cannot be above the target, %d.",
        "edit_sdk_target_below" to "The target cannot be below the minimum, %d.",
        "dev_title" to "Device",
        "dev_tool" to "Android platform-tools",
        "dev_tool_d" to "GutapK talks to the phone with adb, from Google's platform-tools. It is downloaded once, with its size and source shown first.",
        "dev_tool_get" to "Download adb",
        "dev_status" to "Connection",
        "dev_waiting" to "Waiting for a device",
        "dev_g_none" to "Connect a phone",
        "dev_g_none_d" to "On the phone, open Settings, About phone, and tap Build number seven times to unlock Developer options. In Developer options, turn on USB debugging. Plug the phone in with a data cable, and choose File transfer when it asks what the USB connection is for.",
        "dev_g_unauthorized" to "Allow this computer on the phone",
        "dev_g_unauthorized_d" to "The phone asks whether to allow USB debugging from this computer. Tick Always allow from this computer, then tap Allow. Unlock the phone if the question does not show.",
        "dev_g_permission" to "Linux does not let adb open the phone",
        "dev_g_permission_d" to "The USB rules for Android phones are missing. On Debian they come with this package, installed once from a terminal:",
        "dev_g_permission_after" to "Then unplug the phone and plug it in again.",
        "dev_g_offline" to "The phone does not answer",
        "dev_g_offline_d" to "Unplug and replug the cable. If that is not enough, turn USB debugging off and on again in Developer options.",
        "dev_g_other" to "The phone is in another mode",
        "dev_g_other_d" to "It is connected but not running Android normally, in recovery or sideload for example. Restart it into Android.",
        "dev_g_several" to "Several phones are connected",
        "dev_g_several_d" to "Choose the one to work with.",
        "dev_g_auto" to "This window closes by itself when the phone is ready.",
        "dev_mismatch" to "Another adb is running",
        "dev_mismatch_d" to "An adb server of protocol version %d is running, started by another adb program. GutapK's adb is version %d, release %s. Using it restarts that server, which cuts the other program's connections. This command stops it:",
        "dev_mismatch_go" to "Restart with GutapK's adb",
        "dev_t_device" to "Device",
        "dev_t_device_d" to "Model, Android version, battery, storage and users, and restart.",
        "dev_t_apps" to "Apps",
        "dev_t_apps_d" to "The installed apps with their icons, to pull one into the editor.",
        "dev_t_install" to "Install",
        "dev_t_install_d" to "An APK or a split set, onto the phone.",
        "dev_t_files" to "Files",
        "dev_t_files_d" to "Browse the phone's storage, copy files both ways.",
        "dev_t_debloat" to "Debloat",
        "dev_t_debloat_d" to "Remove preinstalled apps you do not use, with a way back.",
        "dev_t_console" to "Console",
        "dev_t_console_d" to "Run adb shell commands and read their output.",
        "dev_restart" to "Restart",
        "dev_restart_go" to "Restart",
        "dev_command" to "Command sent:",
        "dev_r_system" to "Android",
        "dev_r_system_d" to "A normal restart.",
        "dev_r_recovery" to "Recovery",
        "dev_r_recovery_d" to "The recovery menu, to wipe or update from a file.",
        "dev_r_bootloader" to "Bootloader",
        "dev_r_bootloader_d" to "The boot menu fastboot talks to.",
        "dev_z_identity" to "Identity",
        "dev_maker" to "Maker",
        "dev_model" to "Model",
        "dev_codename" to "Code name",
        "dev_serial" to "Serial number",
        "dev_z_system" to "System",
        "dev_patch" to "Security patch",
        "dev_build" to "Build",
        "dev_z_battery" to "Battery",
        "dev_unknown" to "Not read",
        "dev_level" to "Level",
        "dev_state" to "State",
        "dev_b_charging" to "Charging",
        "dev_b_discharging" to "On battery",
        "dev_b_not_charging" to "Plugged in, not charging",
        "dev_b_full" to "Full",
        "dev_temp" to "Temperature",
        "dev_z_storage" to "Storage",
        "dev_free" to "Free",
        "dev_of" to "of %s",
        "dev_used" to "Used",
        "dev_z_users" to "Users",
        "dev_user_id" to "User %d",
        "dev_running" to "running",
        "dev_stopped" to "stopped",
        "job_pull" to "Pulling from the phone",
        "ap_filter" to "Shown",
        "ap_system" to "System apps",
        "ap_system_on" to "The apps that came with the phone",
        "ap_system_off" to "The apps installed by the user",
        "ap_search" to "Search a package name",
        "ap_count" to "%s apps",
        "ap_installer" to "Installed by",
        "ap_installer_none" to "not recorded",
        "ap_first" to "First installed",
        "ap_update" to "Last updated",
        "ap_apks" to "%s APK files:",
        "ap_open" to "Open in the editor",
        "ap_pull_failed" to "The app could not be pulled",
    )

    private val fr: Map<String, String> = mapOf(
        "continue" to "Continuer",
        "back" to "Retour",
        "close" to "Fermer",
        "browse" to "Parcourir",
        "choose_apk" to "Choisir un APK ou un ensemble découpé",
        "accept" to "Compris, continuer",
        "decline" to "Refuser et quitter",
        "step_legal" to "Mentions",
        "step_root" to "Dossier",

        "lang_title" to "Langue",

        "lic_title" to "Licence",

        "legal_title" to "Licences et marques",
        "legal_body" to """GutapK modifie des applications écrites par d'autres. Leurs auteurs gardent leurs droits, et leur licence accompagne chaque copie.

Utiliser et modifier une application sur votre propre appareil vous regarde. Les obligations commencent quand vous DONNEZ l'APK modifié à quelqu'un.

Les licences libres autorisent la modification, sous conditions. Apache-2.0 : conserver les fichiers LICENSE et NOTICE, et indiquer que vous avez modifié le code. GPL-3.0 : la même chose, plus l'obligation de fournir au destinataire le code source complet de VOTRE version modifiée, sous licence GPL, sans restriction ajoutée.

Applications propriétaires : leurs conditions interdisent en général de les modifier ou de les redistribuer. Gardez ce que vous changez pour vous, et lisez les conditions avant de partager quoi que ce soit.

Les noms, logos et icônes sont souvent des marques. Ne présentez pas une application modifiée comme l'originale ni comme officielle. C'est pourquoi GutapK vous permet de renommer une application et de changer son icône.

Un APK modifié est signé avec votre propre clé. Il n'est ni construit, ni relu, ni approuvé par les auteurs de l'original, et il est fourni sans garantie.

Ceci est un résumé en langage courant, pas un avis juridique.""",
        "legal_accepted" to "Accepté, révision %s",

        "root_title" to "Où GutapK doit-il tout ranger ?",
        "root_body" to "Ce dossier contient les outils téléchargés, les dossiers de travail, les journaux et chaque paquet ouvert. GutapK n'écrit nulle part ailleurs, à part ses réglages.",
        "root_field" to "Dossier",
        "root_bad_absolute" to "Indiquez un chemin complet, commençant par / ou ~.",
        "root_bad_forbidden" to "Le système vide les dossiers temporaires et de cache. Choisissez un dossier qui dure.",
        "root_bad_write" to "Ce dossier ne peut pas être créé ou n'est pas accessible en écriture.",
        "root_next_launch" to "Pris en compte au prochain lancement. Ce qui se trouve déjà sous l'ancien dossier y reste.",

        "home_source" to "Commencer",
        "src_apk" to "Modifier un APK",
        "src_apk_d" to "Choisir un APK ou un ensemble découpé, ou le déposer sur cette fenêtre",
        "src_device" to "Appareil ADB",
        "src_device_d" to "Retirer les applications inutiles, récupérer et installer des applications sur un téléphone branché en ADB",
        "drop_here" to "Déposer pour ouvrir",
        "drop_not_apk" to "GutapK ouvre les fichiers .apk et les ensembles découpés (.apks, .xapk, .apkm).",
        "not_yet" to "Pas encore",
        "available" to "Disponible",
        "footer" to "GutapK %s. Logiciel libre sous GNU GPL 3.0 ou ultérieure, sans aucune garantie.",

        "settings" to "Réglages",
        "set_general" to "Général",
        "set_language" to "Langue",
        "set_theme" to "Thème",
        "set_accent" to "Couleur",
        "accent_system" to "Par défaut, GNOME ne définit pas de couleur d'accent",
        "accent_system_named" to "Comme GNOME, %s",
        "accent_blue" to "Bleu",
        "accent_teal" to "Bleu canard",
        "accent_green" to "Vert",
        "accent_yellow" to "Jaune",
        "accent_orange" to "Orange",
        "accent_red" to "Rouge",
        "accent_pink" to "Rose",
        "accent_purple" to "Violet",
        "accent_slate" to "Ardoise",
        "theme_system" to "Comme le système",
        "theme_system_light" to "Comme le système, clair détecté",
        "theme_system_dark" to "Comme le système, sombre détecté",
        "theme_light" to "Clair",
        "theme_dark" to "Sombre",
        "set_storage" to "Stockage",
        "set_root" to "Dossier racine",
        "set_legal" to "Mentions légales",
        "set_licence_d" to "GNU GPL 3.0 ou ultérieure",
        "set_about" to "À propos",
        "about_version" to "Version",
        "about_config" to "Dossier des réglages",
        "set_tools" to "Outils",
        "tool_missing" to "Non installé. Cliquez pour chercher la dernière version.",
        "tool_ok" to "Version %s, vérifié, sha256 %s",
        "tool_checking" to "Installé, vérification en cours",
        "tool_modified" to "Modifié depuis l'installation. Il ne sera pas lancé avant une nouvelle vérification.",
        "tool_failed" to "Échec : %s",
        "tool_state_missing" to "Non installé",
        "tool_state_ok" to "Vérifié",
        "tool_state_bad" to "Modifié",
        "tool_location" to "Emplacement",
        "tool_archive" to "sha256 de l'archive",
        "tool_entry" to "sha256 du programme",
        "job_download" to "Téléchargement",
        "job_check" to "Vérification",
        "job_extract" to "Extraction",
        "cancel" to "Annuler",
        "dl_title" to "%s",
        "dl_what" to "Quoi",
        "dl_from" to "Depuis",
        "dl_size" to "Taille",
        "dl_where" to "Destination",
        "dl_licence" to "Licence",
        "dl_checks" to "Contrôles",
        "dl_checks_v" to "Taille et somme de contrôle telles que publiées par la source. Le sha256 de chaque version est enregistré au premier téléchargement et vérifié avant chaque utilisation.",
        "dl_go" to "Télécharger",
        "home_recent" to "Récents",
        "imp_failed" to "Ce fichier n'a pas pu être ouvert",
        "job_read" to "Lecture",
        "job_copy" to "Copie",
        "ov_reading" to "Lecture du paquet",
        "ov_error" to "Illisible",
        "ov_identity" to "Identité",
        "ov_package" to "Paquet",
        "ov_version" to "Version",
        "ov_min_sdk" to "SDK minimum",
        "ov_target_sdk" to "SDK cible",
        "ov_split" to "Partie d'un bundle",
        "ov_signature" to "Signature",
        "ov_sig_state" to "État",
        "ov_sig_ok" to "Valide, schémas %s",
        "ov_sig_bad" to "Non vérifiée. Non signé, ou modifié après signature.",
        "ov_sig_badge_ok" to "Valide",
        "ov_sig_badge_bad" to "Invalide",
        "ov_content" to "Contenu",
        "ov_dex" to "Fichiers dex",
        "ov_abis" to "ABI",
        "ov_libs" to "Bibliothèques natives",
        "ov_engines" to "Moteurs",
        "ov_trackers" to "Traqueurs",
        "ov_trk_look" to "Chercher les traqueurs",
        "ov_trk_look_d" to "Compare le code de l'application à la liste de traqueurs d'Exodus Privacy. La liste est téléchargée une fois, ses détails affichés d'abord.",
        "ov_trk_none" to "Aucun traqueur connu",
        "ov_trk_none_d" to "Aucun des %s traqueurs de la liste ne correspond. Une bibliothèque dont les noms ont été réduits n'est pas vue.",
        "ov_trk_uncat" to "Sans catégorie",
        "ov_trk_credit" to "Liste de traqueurs par Exodus Privacy, téléchargée le %s, Open Database License.",
        "trk_title" to "Liste de traqueurs d'Exodus Privacy",
        "trk_what" to "Les signatures de code d'environ 400 traqueurs, la liste tenue par Exodus Privacy.",
        "ov_code" to "Code",
        "ov_code_detail" to "%s fichiers dex, %s bibliothèques natives",
        "ov_signer" to "Signataire",
        "ov_algorithm" to "Algorithme",
        "ov_permissions_all" to "Voir toutes les permissions",
        "ov_permissions_more" to "%s et %s autres",
        "ov_permissions_none" to "Aucune permission",
        "ov_permissions_none_detail" to "L'application ne demande rien.",
        "ov_entries" to "Fichiers dans l'archive",
        "ov_none" to "Aucun",
        "ov_file" to "Fichier",
        "ov_location" to "Copie sous la racine",
        "ov_licence_note" to "GutapK ne connaît pas la licence de ce paquet. Vérifiez-la avant de partager quoi que ce soit construit à partir de lui.",
        "ov_permissions" to "Permissions, %s",
        "dl_version" to "Version",
        "dl_looking" to "Recherche de la dernière version sur %s",
        "dl_lookup_failed" to "%s est injoignable : %s",
        "retry" to "Réessayer",
        "self_title" to "GutapK %s est disponible",
        "self_replaces" to "Remplace",
        "self_body" to "La nouvelle AppImage est téléchargée sous la racine, vérifiée avec le sha256 publié par GitHub, puis prend la place de celle-ci. Le fichier actuel est gardé à côté avec .old ajouté. Relancez GutapK pour utiliser la nouvelle version.",
        "self_done_title" to "GutapK mis à jour",
        "self_done" to "%s est la nouvelle version. Relancez GutapK pour l'utiliser. L'ancienne est gardée à côté en .old.",
        "self_failed_title" to "Échec de la mise à jour",
        "self_failed" to "%s. L'AppImage actuelle n'a pas changé.",
        "job_replace" to "Remplacement",
        "upd_title" to "Mise à jour d'outil disponible",
        "upd_go" to "Mettre à jour",
        "upd_later" to "Plus tard",
        "upd_skip" to "Ignorer cette version",
        "upd_none" to "À jour. %s est la dernière version.",
        "upd_check" to "Chercher une mise à jour",
        "upd_auto" to "Chercher les mises à jour au lancement",
        "upd_auto_d" to "Demande à GitHub et aux éditeurs s'il existe des versions plus récentes de GutapK et des outils installés. Rien n'est téléchargé sans votre accord.",
        "disk_title" to "Espace disque",
        "disk_row" to "Ce que GutapK garde sous la racine, et son poids",
        "disk_summary" to "Racine",
        "disk_scanning" to "Mesure en cours",
        "disk_total" to "%s au total",
        "disk_empty" to "Vide",
        "disk_more" to "et %s plus anciens, %s",
        "disk_protected" to "Conservé, en cours d'utilisation ou nécessaire pour vérifier les outils",
        "disk_deletable" to "Peut être supprimé",
        "disk_delete_q" to "Supprimer %s ?",
        "disk_delete_body" to "%s seront libérés. Cette action est définitive.",
        "delete" to "Supprimer",
        "sec_dependencies" to "Outils téléchargés",
        "sec_work" to "Dossiers de travail",
        "sec_logs" to "Journaux",
        "sec_packages" to "Paquets",
        "sec_other" to "Autres fichiers sous la racine",
        "clean_title" to "Libérer de l'espace",
        "clean_go" to "Libérer %s",
        "clean_note" to "Les journaux, les paquets et la clé de signature ne sont pas touchés. Les outils sont retéléchargés au besoin, et comparés aux empreintes déjà enregistrées.",
        "clean_below" to "Le nettoyage est proposé au-delà de %s. En dessous, les %s de téléchargements et de dossiers de travail sont un cache utile, pas du déchet.",
        "job_clean" to "Libération de l'espace",
        "sign_action" to "Signer",
        "sign_title" to "Signer cet APK",
        "sign_key" to "Clé",
        "sign_key_none" to "Pas encore choisie",
        "sign_choose" to "Choisir une clé",
        "sign_change" to "Changer",
        "sign_schemes" to "Schémas de signature",
        "sign_output" to "Fichier signé",
        "sign_go" to "Signer",
        "sign_test_warning" to "La clé de test Android est publique. N'importe qui peut signer avec, donc un APK signé ainsi ne prouve rien sur son auteur. Réservée aux essais.",
        "sign_install_note" to "Android refuse d'installer cet APK par-dessus une application signée avec une autre clé. Désinstallez-la d'abord, ses données partent avec elle.",
        "signed_title" to "Signé et vérifié",
        "signed_file" to "Fichier",
        "signed_signer" to "SHA-256 du certificat",
        "signed_schemes" to "Schémas vérifiés",
        "sign_failed" to "La signature a échoué",
        "show_folder" to "Afficher dans le dossier",
        "job_sign" to "Signature",
        "job_verify" to "Vérification",
        "key_title" to "Clé de signature",
        "key_test" to "Clé de test Android",
        "key_test_d" to "Publique, réservée aux essais",
        "key_own" to "Votre propre clé",
        "key_own_new" to "Créée la première fois que vous la choisissez. Le fichier reste dans le dossier des réglages, son mot de passe dans le trousseau du système.",
        "key_own_ready" to "Prête, SHA-256 %s…",
        "create_title" to "Créer votre clé de signature",
        "create_what_v" to "Une clé RSA 4096 et un certificat autosigné nommé GutapK signing key, valable 30 ans.",
        "create_password" to "Mot de passe",
        "create_password_v" to "Aléatoire, gardé dans le trousseau du système sous le nom GutapK signing keystore. Le trousseau peut demander votre mot de passe de session.",
        "create_backup" to "Sauvegardez le fichier de clé et gardez son entrée dans le trousseau. Android ne met à jour une application que si elle est signée avec la même clé. Si l'un des deux est perdu, il faudra désinstaller l'application, avec ses données, avant d'installer une nouvelle version.",
        "create_go" to "Créer",
        "creating" to "Création de votre clé",
        "creating_note" to "Générer une clé de 4096 bits prend quelques secondes. Le trousseau peut demander votre mot de passe de session.",
        "create_failed" to "La clé n'a pas pu être créée",
        "own_missing" to "Votre propre clé est choisie, mais %s est absent. Remettez le fichier en place ou choisissez une autre clé.",
        "set_key_file" to "Fichier de clé",
        "job_keygen" to "Génération de la clé",
        "job_keystore" to "Écriture du coffre",
        "job_keyring" to "Enregistrement dans le trousseau",
        "set_signing" to "Signature",
        "set_sign_key" to "Clé de signature",
        "edit_permissions" to "Permissions",
        "edit_perm_note" to "Désactivez une permission pour la retirer. Cela peut empêcher une fonction de marcher. Ajouter une permission n'est pas proposé, une application ne peut pas recevoir plus que ce pour quoi elle a été conçue.",
        "edit_title" to "Modifier cette application",
        "edit_min_sdk" to "SDK min",
        "edit_target_sdk" to "SDK cible",
        "ok" to "OK",
        "edit_changed" to "Modifié",
        "edit_nothing_yet" to "Modifiez quelque chose pour reconstruire",
        "edit_needs_key" to "Choisissez une clé pour reconstruire",
        "edit_zone_sdk" to "Versions d'Android",
        "edit_zone_icon" to "Icône",
        "edit_zone_signing" to "Signature",
        "edit_retry" to "Réessayer avec apktool",
        "edit_retry_note" to "APKEditor n'a pas pu reconstruire cette application. apktool, le second moteur, reconstruit avec aapt2 de Google et peut réussir là où APKEditor échoue. Il est téléchargé et vérifié d'abord s'il n'est pas installé, chaque étape dans le journal de la tâche.",
        "edit_zone_modern" to "Moderniser",
        "edit_back" to "Retour prédictif",
        "edit_back_d" to "Android 14 et plus montrent l'écran de destination pendant le geste de retour. Une application qui intercepte encore Retour à l'ancienne peut ne plus fermer ses propres panneaux avec.",
        "edit_back_done" to "Déjà activé.",
        "edit_locales" to "Langues de l'application",
        "edit_locales_d" to "Android 13 et plus permettent de choisir la langue de l'application dans les Paramètres, parmi celles dans lesquelles elle est traduite.",
        "edit_locales_done" to "Déjà listée dans les Paramètres.",
        "edit_libs" to "Bibliothèques natives depuis l'APK",
        "edit_libs_d" to "Les bibliothèques restent stockées dans l'APK au lieu d'être copiées à l'installation : moins d'espace et une installation plus rapide.",
        "edit_libs_done" to "Déjà lues depuis l'APK.",
        "edit_libs_none" to "Cette application n'a pas de bibliothèque native.",
        "edit_trk_first" to "Cherchez d'abord les traqueurs dans l'aperçu, il télécharge la liste d'Exodus Privacy.",
        "edit_trk_none" to "Aucun traqueur connu dans cette application.",
        "edit_trk_note" to "Un traqueur neutralisé voit ses composants désactivés et, pour Firebase et Facebook, les réglages de refus documentés par leurs éditeurs activés. Le code que l'application appelle elle-même tourne encore.",
        "edit_trk_parts" to "%s composants désactivés",
        "edit_trk_no_parts" to "Aucun composant propre, réglages de refus seulement",
        "edit_trk_ads" to "Une régie publicitaire : l'application peut planter en voulant afficher une pub.",
        "edit_adid" to "Identifiant publicitaire",
        "edit_adid_d" to "Retire la permission de lire l'identifiant publicitaire. Android 13 et plus ne donnent alors que des zéros à l'application.",
        "edit_zone_size" to "Taille",
        "edit_abi" to "Architectures",
        "edit_abi_one" to "Seulement %s, rien à retirer.",
        "edit_abi_all" to "Toutes gardées : %s. Les téléphones actuels sont en arm64-v8a.",
        "edit_abi_only" to "%s seulement",
        "edit_abi_keep_all" to "Tout garder",
        "edit_langs" to "Langues",
        "edit_langs_one" to "Une seule langue, rien à retirer.",
        "edit_langs_all" to "Les %s gardées.",
        "edit_langs_some" to "%s sur %s gardées. Les autres reviennent à la langue par défaut de l'application.",
        "edit_debuginfo" to "Infos de débogage",
        "edit_debuginfo_d" to "Retire les numéros de ligne et les noms de variables du code. Un rapport de plantage n'indique alors plus de ligne. Gain faible sur une application déjà réduite par son éditeur.",
        "edit_zone_security" to "Sécurité",
        "edit_nobackup" to "Pas de sauvegarde",
        "edit_nobackup_d" to "Les données de l'application restent hors de la sauvegarde cloud de Google et de la sauvegarde adb. Sur Android 12 et plus, un transfert vers un nouveau téléphone suit les règles de l'application.",
        "edit_nobackup_done" to "Sauvegarde déjà désactivée.",
        "edit_net" to "Réseau strict",
        "edit_net_d" to "Refuse le http en clair et les certificats ajoutés par l'utilisateur, ceux qui servent à espionner le trafic. Une application qui parle en http en clair à un appareil de votre réseau, caméra ou imprimante, peut le perdre.",
        "edit_fragile" to "Demander avant d'effacer les données",
        "edit_fragile_d" to "La désinstallation demande s'il faut garder les données de l'application, pour les retrouver à la réinstallation.",
        "edit_fragile_done" to "Demande déjà.",
        "edit_memtag" to "Marquage mémoire",
        "edit_memtag_d" to "Sur les téléphones avec marquage mémoire, Pixel 8 et plus, les erreurs mémoire sont bloquées au lieu d'être exploitées. Une application défaillante peut alors s'arrêter là où elle continuait.",
        "edit_memtag_done" to "Déjà activé.",
        "edit_debug" to "Non débogable",
        "edit_debug_d" to "Cette application est débogable : tout ordinateur auquel elle est branchée peut lire ses données. À désactiver pour un usage quotidien.",
        "edit_debug_done" to "Non débogable, comme il se doit.",
        "edit_package" to "Id de package",
        "edit_package_note" to "Un nouvel id crée un clone qui s'installe à côté de l'original. L'id, ses providers et ses propres permissions changent aussi là où le code et les ressources les écrivent en entier. Les services Google liés à l'id d'origine, connexion ou cartes par exemple, cessent de marcher dans le clone.",
        "edit_package_format" to "Des mots en minuscules reliés par des points, chacun commençant par une lettre, comme com.example.app.",
        "edit_package_reserved" to "Réservé à Android, Google ou un système : android, com.android, com.google, org.lineageos, org.grapheneos.",
        "edit_icon_image" to "Remplacer par une image",
        "edit_icon_image_d" to "Un PNG carré, d'au moins %s px. Placé dans la zone sûre de l'icône, sur le fond propre à l'application.",
        "edit_icon_image_ok" to "%s, %s px",
        "edit_icon_clear" to "Retirer",
        "edit_icon_not_png" to "%s n'est pas un fichier PNG.",
        "edit_icon_not_square" to "%s n'est pas carrée.",
        "edit_icon_too_small" to "%s fait %s px, il faut au moins %s px.",
        "edit_icon_unreadable" to "%s ne peut pas être lue comme une image.",
        "edit_themed_icon" to "Icône à thème",
        "edit_themed_note" to "Permet à Android 13 et plus de colorer l'icône avec les couleurs du fond d'écran. Construite à partir du premier plan de l'icône, idéale pour un logo sur fond transparent.",
        "edit_themed_done" to "Déjà à thème, rien à ajouter.",
        "edit_themed_legacy" to "Indisponible : l'icône est une image simple, pas une icône adaptative.",
        "edit_themed_none" to "Indisponible : l'application ne déclare pas d'icône.",
        "rename_action" to "Modifier",
        "rename_title" to "Renommer cette application",
        "rename_field" to "Nom affiché",
        "rename_go" to "Reconstruire et signer",
        "rename_needs_tool" to "APKEditor est nécessaire pour reconstruire l'APK. Il sera téléchargé et vérifié la première fois, les détails affichés avant tout téléchargement.",
        "job_decode" to "Décodage",
        "job_edit" to "Modification",
        "job_build" to "Reconstruction",
        "apk_filter" to "APK et ensembles découpés",
        "job_merge" to "Fusion de l'ensemble découpé",
        "set_incomplete" to "Cet ensemble découpé est incomplet",
        "set_found" to "Trouvé : %s",
        "set_add" to "Ajouter des fichiers",
        "set_no_apk" to "Aucun APK dans ces fichiers.",
        "set_no_base" to "L'APK de base manque. Il s'appelle souvent base.apk, ou porte le nom de l'application.",
        "set_several_bases" to "Plusieurs APK de base ont été donnés. Gardez les fichiers d'une seule application et d'une seule version.",
        "set_mixed_packages" to "Ces fichiers appartiennent à des applications différentes : %s.",
        "set_mixed_versions" to "Ces fichiers viennent de versions différentes de l'application.",
        "set_duplicate" to "La partie %s a été donnée deux fois, dans deux versions différentes.",
        "set_missing_types" to "Des parties manquent : %s.",
        "set_missing_unknown" to "L'APK de base a besoin de ses parties, aucune n'a été donnée.",
        "set_unity_lib" to "C'est un jeu Unity et sa bibliothèque moteur manque. Ajoutez la partie qui porte le nom du processeur, par exemple split_config.arm64_v8a.apk.",
        "set_type_abi" to "processeur (ABI)",
        "set_type_density" to "densité d'écran",
        "set_type_language" to "langue",
        "set_merge_needs" to "APKEditor fusionne les parties en un seul APK que GutapK peut lire et modifier.",
        "ov_set" to "Ensemble découpé",
        "ov_set_d" to "%s parties fusionnées : %s",
        "ov_obb" to "Fichiers d'extension (OBB)",
        "ov_obb_note" to "Les fichiers d'extension ne font pas partie de l'APK et n'ont pas été fusionnés. Ils vont sur l'appareil séparément.",
        "un_title" to "Unity",
        "un_version" to "Version de Unity",
        "un_unknown" to "Introuvable",
        "un_backend" to "Moteur de script",
        "un_il2cpp" to "IL2CPP, C# compilé en code natif",
        "un_mono" to "Mono, C# gardé en assemblages .NET",
        "un_engine_abis" to "Moteur compilé pour",
        "un_missing" to "Absent",
        "un_metadata" to "Métadonnées",
        "un_metadata_version" to "version %s",
        "un_metadata_unreadable" to "en-tête non reconnu",
        "un_assemblies" to "Assemblages",
        "un_assemblies_d" to "%s fichiers .dll dans assets/bin/Data/Managed",
        "un_no_metadata" to "Aucun global-metadata.dat trouvé. Le jeu peut le renommer ou l'intégrer à la bibliothèque, ce qu'un dump ne sait pas lire tel quel.",
        "un_protected" to "Les métadonnées ne commencent pas par la signature d'IL2CPP. Elles sont très probablement chiffrées ou obscurcies, et un dump échouera dessus tel quel.",
        "un_no_lib" to "libil2cpp.so est absent. Si cet APK faisait partie d'un ensemble découpé, ouvrez l'ensemble complet.",
        "job_dump" to "Dump du code IL2CPP",
        "un_methods" to "Méthodes",
        "un_methods_d" to "%s méthodes avec leur offset, pour %s",
        "un_methods_none" to "Pas encore extraites. Cpp2IL lit le jeu et liste chaque méthode avec son offset dans libil2cpp.so.",
        "un_dump_needs" to "Cpp2IL liste chaque méthode du jeu avec son offset dans libil2cpp.so. Il ne publie que des pré-versions.",
        "un_dump_failed" to "Le dump a échoué",
        "me_title" to "Méthodes",
        "me_source" to "%s méthodes, %s, Unity %s",
        "me_search" to "Chercher un namespace, un type ou une méthode",
        "me_hint" to "Tapez une partie d'un nom. Plusieurs mots affinent la recherche, dans n'importe quel ordre.",
        "me_none" to "Aucune méthode ne correspond.",
        "me_count" to "%s résultats",
        "me_length" to "%s octets",
        "me_more" to "Seuls les %s premiers sont affichés. Ajoutez un mot pour affiner la recherche.",
        "un_patches" to "Patches d'octets",
        "un_patches_d" to "%s enregistrés, appliqués à la reconstruction",
        "hex_edit" to "Modifier des octets",
        "hex_zone" to "Octets de libil2cpp.so, %s",
        "hex_where" to "Offset dans le fichier",
        "hex_truncated" to "Seuls les %s premiers octets de cette méthode sont affichés et modifiables.",
        "hex_patches" to "Patches dans cette méthode, %s",
        "hex_patches_none" to "Aucun pour l'instant.",
        "hex_not_applied" to "Les patches sont enregistrés avec ce package et appliqués par Reconstruire et signer, dans l'écran Modifier.",
        "hex_remove_title" to "Retirer ce patch ?",
        "hex_remove" to "Retirer",
        "hex_offset" to "Offset, en hexa",
        "hex_bytes" to "Nouveaux octets, en hexa",
        "hex_bytes_help" to "Paires de chiffres hexa, espaces permis, par exemple 20 00 80 52",
        "hex_bad" to "Uniquement des paires de chiffres hexa, de 0 à 9 et de A à F.",
        "hex_range" to "Restez entre %s et %s, dans cette méthode.",
        "hex_same" to "Ce sont déjà les octets présents.",
        "hex_overlap" to "Cela chevauche le patch à %s. Retirez-le d'abord.",
        "hex_replaces" to "Remplace %s",
        "hex_save" to "Enregistrer",
        "edit_patches" to "Appliquer %d patches d'octets",
        "edit_patches_d" to "Chaque patch vérifie d'abord les octets qu'il remplace. Si l'un ne correspond pas, rien n'est écrit et la reconstruction s'arrête.",
        "edit_patches_abi" to "Des patches visent %s, que le réglage processeur ci-dessus retire. Gardez ce processeur ou désactivez les patches.",
        "edit_patches_blocked" to "Des patches visent un processeur retiré",
        "edit_sdk_range" to "Entre %d et %d.",
        "edit_sdk_min_above" to "Le minimum ne peut pas dépasser la cible, %d.",
        "edit_sdk_target_below" to "La cible ne peut pas être sous le minimum, %d.",
        "dev_title" to "Appareil",
        "dev_tool" to "Android platform-tools",
        "dev_tool_d" to "GutapK parle au téléphone avec adb, issu des platform-tools de Google. Il est téléchargé une fois, avec sa taille et sa source affichées avant.",
        "dev_tool_get" to "Télécharger adb",
        "dev_status" to "Connexion",
        "dev_waiting" to "En attente d'un appareil",
        "dev_g_none" to "Branchez un téléphone",
        "dev_g_none_d" to "Sur le téléphone, ouvrez Paramètres, À propos du téléphone, et touchez sept fois Numéro de build pour débloquer les Options pour les développeurs. Dans ces options, activez le Débogage USB. Branchez le téléphone avec un câble de données, et choisissez Transfert de fichiers quand il demande l'usage de la connexion USB.",
        "dev_g_unauthorized" to "Autorisez cet ordinateur sur le téléphone",
        "dev_g_unauthorized_d" to "Le téléphone demande s'il faut autoriser le débogage USB depuis cet ordinateur. Cochez Toujours autoriser depuis cet ordinateur, puis touchez Autoriser. Déverrouillez le téléphone si la question n'apparaît pas.",
        "dev_g_permission" to "Linux n'autorise pas adb à ouvrir le téléphone",
        "dev_g_permission_d" to "Les règles USB des téléphones Android manquent. Sur Debian, elles viennent avec ce paquet, à installer une fois depuis un terminal :",
        "dev_g_permission_after" to "Ensuite, débranchez puis rebranchez le téléphone.",
        "dev_g_offline" to "Le téléphone ne répond pas",
        "dev_g_offline_d" to "Débranchez et rebranchez le câble. Si cela ne suffit pas, désactivez puis réactivez le Débogage USB dans les Options pour les développeurs.",
        "dev_g_other" to "Le téléphone est dans un autre mode",
        "dev_g_other_d" to "Il est branché mais ne tourne pas sous Android normalement, en recovery ou en sideload par exemple. Redémarrez-le sous Android.",
        "dev_g_several" to "Plusieurs téléphones sont branchés",
        "dev_g_several_d" to "Choisissez celui avec lequel travailler.",
        "dev_g_auto" to "Cette fenêtre se ferme toute seule quand le téléphone est prêt.",
        "dev_mismatch" to "Un autre adb tourne",
        "dev_mismatch_d" to "Un serveur adb de version de protocole %d tourne, lancé par un autre programme adb. L'adb de GutapK est en version %d, release %s. L'utiliser redémarre ce serveur, ce qui coupe les connexions de l'autre programme. Cette commande l'arrête :",
        "dev_mismatch_go" to "Redémarrer avec l'adb de GutapK",
        "dev_t_device" to "Appareil",
        "dev_t_device_d" to "Modèle, version d'Android, batterie, stockage et utilisateurs, et redémarrage.",
        "dev_t_apps" to "Applications",
        "dev_t_apps_d" to "Les applications installées avec leur icône, pour en envoyer une dans l'éditeur.",
        "dev_t_install" to "Installer",
        "dev_t_install_d" to "Un APK ou un ensemble découpé, sur le téléphone.",
        "dev_t_files" to "Fichiers",
        "dev_t_files_d" to "Parcourir le stockage du téléphone, copier des fichiers dans les deux sens.",
        "dev_t_debloat" to "Nettoyage",
        "dev_t_debloat_d" to "Retirer les applications préinstallées inutiles, avec un retour possible.",
        "dev_t_console" to "Console",
        "dev_t_console_d" to "Lancer des commandes adb shell et lire leur sortie.",
        "dev_restart" to "Redémarrer",
        "dev_restart_go" to "Redémarrer",
        "dev_command" to "Commande envoyée :",
        "dev_r_system" to "Android",
        "dev_r_system_d" to "Un redémarrage normal.",
        "dev_r_recovery" to "Recovery",
        "dev_r_recovery_d" to "Le menu recovery, pour effacer ou mettre à jour depuis un fichier.",
        "dev_r_bootloader" to "Bootloader",
        "dev_r_bootloader_d" to "Le menu de démarrage auquel parle fastboot.",
        "dev_z_identity" to "Identité",
        "dev_maker" to "Fabricant",
        "dev_model" to "Modèle",
        "dev_codename" to "Nom de code",
        "dev_serial" to "Numéro de série",
        "dev_z_system" to "Système",
        "dev_patch" to "Correctif de sécurité",
        "dev_build" to "Build",
        "dev_z_battery" to "Batterie",
        "dev_unknown" to "Non lu",
        "dev_level" to "Niveau",
        "dev_state" to "État",
        "dev_b_charging" to "En charge",
        "dev_b_discharging" to "Sur batterie",
        "dev_b_not_charging" to "Branché, pas en charge",
        "dev_b_full" to "Pleine",
        "dev_temp" to "Température",
        "dev_z_storage" to "Stockage",
        "dev_free" to "Libre",
        "dev_of" to "sur %s",
        "dev_used" to "Utilisé",
        "dev_z_users" to "Utilisateurs",
        "dev_user_id" to "Utilisateur %d",
        "dev_running" to "actif",
        "dev_stopped" to "arrêté",
        "job_pull" to "Récupération depuis le téléphone",
        "ap_filter" to "Affichage",
        "ap_system" to "Applications système",
        "ap_system_on" to "Les applications livrées avec le téléphone",
        "ap_system_off" to "Les applications installées par l'utilisateur",
        "ap_search" to "Chercher un nom de package",
        "ap_count" to "%s applications",
        "ap_installer" to "Installée par",
        "ap_installer_none" to "non enregistré",
        "ap_first" to "Première installation",
        "ap_update" to "Dernière mise à jour",
        "ap_apks" to "%s fichiers APK :",
        "ap_open" to "Ouvrir dans l'éditeur",
        "ap_pull_failed" to "L'application n'a pas pu être récupérée",
    )

    val tables: Map<Lang, Map<String, String>> = mapOf(Lang.EN to en, Lang.FR to fr)
}
